### ISSUE TITLE
Clicking different lines and typing sometimes inserts text from other lines

### ISSUE THREAD

**Issue by michaelcox** [facebook/draft-js#1382]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
See this video:
https://www.useloom.com/share/0863d42b72f64d1e8c53ac851065a132

You can reproduce like this:
  * Copy in a few lines of text - in the screen share I did 4 lines of lorem ipsum
  * Click on each line, one at a time, and type in some text. In my screen share I just typed in 1 or 2 characters each time after I clicked to the new line.
  * Sometimes sooner, sometimes later, Draft will copy the text from one line and put it on another line.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

This works with the sample fiddle. No changes necessary.

**What is the expected behavior?**
I would expect Draft to only insert the characters I type, not content from other unrelated lines.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Tested on Chrome `61.0.3163.79` / OSX where I see this issue. Also broken in Safari `10.1.2`. But - works as expected in Firefox `55.0.3`.

**Comment by colinjeanne** [comment]
This looks similar to #989

**Comment by michaelcox** [comment]
Agreed. It's more than just a loss of cursor position, but I see the gif you created in #989 also shows the problem with copying the content from another line. I'll close this in favor of that ticket which already has more history.

**Comment by againksy** [comment]
@colinjeanne @michaelcox Anybody found the solution? how to fix this?

**Comment by colinjeanne** [comment]
@againksy, there is a longer discussion in #989. My team had found a solution but Draft has changed since we implemented it in our fork and we haven't had time to rectify it with what's currently in Draft.

**Comment by againksy** [comment]
@colinjeanne , Dear is on draft 0.10 version this still occurs? i am now on 0.9.1, maybe if ill move to 10, it will fix?
