### ISSUE TITLE
Demo Site: Scrolling down and clicking into Textarea jumps viewport to top.

### ISSUE THREAD

**Issue by thoughtpalette** [facebook/draft-js#14]
Chrome Version 48.0.2564.109 (64-bit)/Yosemite.

![](https://i.gyazo.com/e2c1671ad46bec9df1a2f090f06915a9.gif)

Steps:
1: Scroll down page
2: Click textarea

**Comment by hellendag** [comment]
Weird. Are you using any browser plugins or extensions?

**Comment by thoughtpalette** [comment]
Just Privacy Badger. Though the behavior is reproducible with or without it enabled. :|

**Comment by hellendag** [comment]
I don't think I've seen this, and we can't repro it here. Do you see the same issue when focusing a comment input on www.facebook.com?

**Comment by tjisousa** [comment]
I'm using the exact same Chrome version as you and I can't reproduce this.

**Comment by thoughtpalette** [comment]
Hmmm. Just tested on an incognito tab with no add-ons and I still have the same behavior. 

I'm not able to reproduce this behavior on an FB comment input. 

I do however receive some react based console errors/warnings. Probably unrelated.

<img width="806" alt="screen shot 2016-02-22 at 4 31 27 pm" src="https://cloud.githubusercontent.com/assets/690624/13235100/c82888da-d981-11e5-831b-64c135b5bdaf.png">

**Comment by JaRail** [comment]
Seeing similar issues in Safari on the Draft.js site.

Zoom in on text box, click somewhere to position to the cursor.

Result: Even though the textbox is completely in view, the viewport jumps to left: 0 and some top: 0+scroll(?) offset.

The window size can affect if you can scroll. So depending on if you've scrolled (unzoomed) or not, you might be jumped to the top-left or some lower position based on the scroll..

**Comment by knowbody** [comment]
works fine for me on Chrome Version 48.0.2564.109 (64-bit) / Yosemite

**Comment by brwr** [comment]
I'm able to reproduce in Chrome Version 48.0.2564.103 (64-bit) on OS X El Capitan Version 10.11.1.

Maybe an El Capitan problem? I've noticed a lot of problems with various projects/programs/things since upgrading.

**Comment by hellendag** [comment]
I can repro the jump in Safari described by @JaRail with pinch+zoom. Not sure if it's the same issue, but still worth investigating.

Still can't repro the original issue in Chrome. I'm also on El Capitan 10.11.3.

**Comment by JaRail** [comment]
**Also repros in the FB feed!**

This is a bigger problem than we may have thought. With pinch & zoom in safari on mac, I am getting some jumping in the main FB feed.

1) Zoom in on post in your feed
2) Click comment box

Result: View is positioned to left:0. Vertical position remains unchanged.
Expected: No change in viewport position

**Comment by JaRail** [comment]
Can also repro in Chrome on mac with same steps as Safari. I could not repro in Firefox Dev Edition as it doesn't seem to support pinch & zoom o_O

**Comment by hellendag** [comment]
Thanks all, this is really helpful.

I'm fairly sure this is related to scroll management during focus, here: https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L328

**Comment by bloodyowl** [comment]
Tracked down the reason why it fails, and this comes down to fbjs.

https://github.com/facebook/fbjs/blob/3df1c679208d405b5996fee684c9527a034e2f01/src/core/dom/getScrollPosition.js#L31-L34

What occurs when `window` is the scrollParent in a webkit browser is that `document.body` is used for the measurements, where `document.documentElement` is the right element to check:

https://github.com/facebook/fbjs/blob/3df1c679208d405b5996fee684c9527a034e2f01/src/core/dom/getDocumentScrollElement.js#L15-L17

This results in an incorrect scroll position:

<img width="540" alt="screen shot 2016-02-29 at 11 14 45" src="https://cloud.githubusercontent.com/assets/1688645/13391608/b16b47e6-ded5-11e5-9716-c28b562bf05e.png">

**Comment by bloodyowl** [comment]
just tested, and focus has the expected behaviour in chrome when the `isWebkit` condition is removed.  https://github.com/facebook/fbjs/blob/3df1c679208d405b5996fee684c9527a034e2f01/src/core/dom/getDocumentScrollElement.js#L30

**Comment by AlastairTaft** [comment]
I get this issue on chrome\MAC. To get around it for now I'm using my own version of focus that calls the `getUnboundedScrollPosition` instead of `getScrollPosition`.

I can see that the problem area seems to be [the following lines](https://github.com/facebook/fbjs/blob/3df1c679208d405b5996fee684c9527a034e2f01/src/core/dom/getScrollPosition.js#L42-L43). 

<img width="618" alt="screen shot 2016-03-13 at 12 19 23 am" src="https://cloud.githubusercontent.com/assets/3320742/13723201/ee9e5a8c-e8b1-11e5-9d14-6e8627d03c52.png">
(Passing in `window` to the function)

<img width="847" alt="screen shot 2016-03-13 at 12 21 55 am" src="https://cloud.githubusercontent.com/assets/3320742/13723204/112834ce-e8b2-11e5-83d6-042b86bad169.png">
At this point you can see that the value of yMax is going to be 0 which means the value passed back will always be `y: 0`

Something's not right here but I don't think it's using the correct element for viewport. The `document.documentElement` is the `<html />` element when I think what it should be using here is the `<body />` element. Else the `clientHeight` will always be the same as the `scrollHeight`.

Created a pull request [here](https://github.com/facebook/fbjs/pull/130).

**Comment by victorhaggqvist** [comment]
Can reproduce with ArchLinux Chrome Version 51.0.2687.0 dev (64-bit), but it works with Chromium Version 49.0.2623.110 (64-bit).
Tested on https://facebook.github.io/draft-js/ which atm claims Draft v0.3.0, ReactDOM v0.14.7, React v0.14.7.
Tested on the thing i was working on as well, Draft v0.3.0, ReactDOM v15.0.0-rc.2, React v15.0.0-rc.2, with the same result.

**Comment by devhero** [comment]
@hellendag it's still broken on Chrome 51.0.2704.84 (64-bit) on OSX El Capitan.

**Comment by alexeygolev** [comment]
It's works ok for me in Chrome 51.0.2704.84 on OSX El Capitan... weird

**Comment by devhero** [comment]
@alexeygolev sorry, I made a mistake. the official draft-js page works correctly, even the examples. Instead, using it with my bundled libraries, even in a polished page, the issue still appear. IMHO it's a combination of libraries but it's complicated to find the match.

**Comment by linzerui** [comment]
Works correctly in production. But if develop in a "localhost://" it happens.

**Comment by appsforartists** [comment]
Seeing it in both these editors:

https://facebook.github.io/draft-js/
https://www.draft-js-plugins.com/

On a Chromebook running version 51.0.2704.106.  Thankfully not seeing it on Facebook.com, though I've certainly seen plenty of scroll management bugs there in the past.

**Comment by tylercraft** [comment]
I'm not able to duplicate with Chrome 54.0.2840.59 or Safari 10.0 (12602.1.50.0.10) on either of these pages:

https://facebook.github.io/draft-js/
https://www.draft-js-plugins.com/

Therefore I'm going to close this out.

**Comment by Prinzhorn** [comment]
I'm on Ubuntu and I'm seeing the same on Chromium 53.0.2785.143 but not on Chrome 54.0.2840.90

## Chromium

![screenshot from 2016-11-11 10 39 53](https://cloud.githubusercontent.com/assets/679144/20210758/6bfdd2a6-a7fb-11e6-9ad3-abaaceb73e01.png)

## Chrome

![screenshot from 2016-11-11 10 40 08](https://cloud.githubusercontent.com/assets/679144/20210764/70347b4a-a7fb-11e6-9522-c53d5bd23d37.png)


Two things:

1. Why on earth does Chromium behave different from Chrome?
2. UA sniffing is bad and you should feel bad. Removing the "isWebkit" hack fixes it in Chromium.

**Comment by dtipson** [comment]
This might have to do with the change to ref: it's now recommended to be a function that sets a context value instead of a string.

**Comment by gwrhamilton** [comment]
The problem is fixed for me on Chrome Version 56.0.2924.87 (64-bit) but comes back if chrome://flags **Experimental Web Platform features** is turned on.

Don't know if that is an issue or not?

**Comment by optimatex** [comment]
I got the same problem. But for my case disabling Experimental Web Platform features solved the problem.

**Comment by teod** [comment]
I still can reproduce this issue using Google Chrome Canary Version 61.0.3154.0

**Comment by yujiangshui** [comment]
I got the same problem using Google Chrome Canary Version 62.0.3174.0 (Official Build) Canary (64-bit), but it works fine in Google Chrome Version 59.0.3071.115 (Official Build) (64-bit) and Safari.

And some of my customers feedback they have this problem. We need to reopen this issue @tylercraft

**Comment by sophiebits** [comment]
The bug in Chrome 61 should be fixed if you update your node modules to include fbjs 0.8.15 (just released) as Draft's dependency.

**Comment by sophiebits** [comment]
(If you do a hard reload on draftjs.org and try again, it should be fixed there.)

**Comment by teod** [comment]
@sophiebits I tried to include fbjs@0.8.15 in my modules, still experiencing this issue.

**Comment by sophiebits** [comment]
`yarn upgrade fbjs` should do the trick. Otherwise yarn is going to reuse the existing lockfile.

**Comment by MarkSMT** [comment]
Scrolling is still broken in chrome 61 (stable release cycle). Just noticed today.

**Comment by tuan072090** [comment]
This error happen when I upgrade to v0.10.1, just downgrade to v0.10.0 and everything work fine :D

**Comment by meirkoen** [comment]
Make sure you have the following css setting:

html{
  height: 100%;
}

If not, the value of window.document.documentElement.clientHeight will be the same as the value of window.document.documentElement.scrollHeight and this is the cause of this bug.
