### ISSUE TITLE
Editor scrolls to bottom when pressing enter in the middle of a big paragraph

### ISSUE THREAD

**Issue by jainp** [facebook/draft-js#304]
When you have a big paragraph and you press enter in the middle, instead of keeping the focus in the middle of the page, the editor scrolls all the way to the bottom.

Steps to reproduce:
1. Go to https://facebook.github.io/draft-js/
2. Copy paste in a large continuous paragraph without any newlines in between.
3. Scroll to the middle of the big paragraph and press enter.
4. The editor will have scrolled to the bottom

This doesn't seem to happen consistently all the time, but I've seen it come up enough times on big paragraphs.

**Comment by hellendag** [comment]
How many characters in the paragraph?

**Comment by jainp** [comment]
I tested with about 8000 characters in one paragraph. It generally occurs when the paragraph is big enough that I need to scroll to see all of it. If I scroll to the somewhere in the middle and press enter, that's when the editor scrolls to the bottom.

**Comment by hellendag** [comment]
Ok, I'll check it out.

What's the use case for an 8000-character paragraph, btw? :)

**Comment by jainp** [comment]
The 8000 was just to make the bug appear on desktop :). My use case was on
mobile where the paragraph can easily go past the visible screen area (with
much fewer characters) and the auto scrolling to the bottom becomes much
more pronounced.

**Comment by johanneslumpe** [comment]
@jainp @hellendag It doesn't matter what the paragraph length it. This bug occurs when a block is split and the end of the block is outside of the viewport. It can be reproduced by using very little test and just positioning the editor in a way that the paragraph isn't fully visible in the viewport.

**Comment by johanneslumpe** [comment]
@hellendag unfortunately I have no time right not to investigate this any further, but I've tracked down the issue to this line: https://github.com/facebook/draft-js/blob/master/src/model/transaction/splitBlockInContentState.js#L61

Removing the selection merging gets rid of the scrolling issue but obviously leaves the selection in the previous block. So I assume it has something to do with the way the selection is updated.

**Comment by houkanshan** [comment]
I think it's this line?

https://github.com/facebook/draft-js/blob/5d5f1b4b89c509d17697965ce9a0d596ed220c43/src/component/contents/DraftEditorBlock.react.js#L103

If it's bottom is outside of the viewport (`scrollDelta > 0`), a scrolling will be performed, and the scrolling intend to align the bottom of the block with the bottom of the viewport.

**Comment by michelson** [comment]
Hi @hellendag ,
I've made a PR #775 that fixes this issue, it fails one test case related on the calculation of scroll , before update that test case I would like to know if you would accept this change. I've tested manually and it works.
This is a really blocking bug in terms of UX imho, I hope we can solve this soon.

best

**Comment by michelson** [comment]
thinking it twice, maybe it would be a good idea to not calculate scroll deltas at all, and just scroll into the current cursor (the active element) after enter. 
Any thoughts ?

**Comment by Rezaaa** [comment]
I have this issue too. When do you plan to fix it? @hellendag

**Comment by erisnuts** [comment]
Is there any progress on this issue. It'sreally a lot of pain for my team. @hellendag ?

**Comment by michelson** [comment]
In my Draft implementation on my text editor I've added some logic on handleReturn, it's not optimal, but at least improves the UX on this issue.
you can see the solution at: https://github.com/michelson/dante2/blob/master/src/components/dante_editor.js#L574

**Comment by hhlevnjak** [comment]
Hi, is there any progress on fixing this? It seems this is still an issue in the latest version.

**Comment by tarun-dugar** [comment]
still facing this issue :(

**Comment by MarkSMT** [comment]
@hellendag This is a major issue, but looks like it is being neglected, is it ever going to be fixed?

**Comment by andpor** [comment]
This is a very serious issues, how come it is not yet addressed?

The use cases are very simple, having paragraphs with 8000 chars is not needed. I have 3 editors on one page with each tall enough for 6-7 lines of text per size of view, they are vertically scrollable. Once I have more then 7 lines of text, any edit with return pressed  in the top visible lines is auto-scrolling the editor to the end. This is a showstopper for us...no user will be willing to accept this scrollbar jumping behaviour.

Please fix asap.

**Comment by andpor** [comment]
The demos for [this draft fork](https://jpuri.github.io/react-draft-wysiwyg) do not suffer same fate. Return works quite well...

**Comment by andpor** [comment]
@houkanshan - you are correct. That line of code causes the issue. I commented it out and now all editors everywhere work fine. The calculations or the logic is 100% incorrect.

Please fix this!

**Comment by andpor** [comment]
The fix is TRIVIAL.

change this line:
`var scrollBottom = scrollParent.offsetHeight + scrollPosition.y;`

to read:
`var scrollBottom = scrollParent.offsetTop + scrollParent.offsetHeight + scrollPosition.y;`

Why would it take so long to fix ????

**Comment by howardjing** [comment]
@andpor, if you could submit a PR with that fix, that would be great!

**Comment by andpor** [comment]
Will do

**Comment by andpor** [comment]
What should be the target branch for this PR - anybody knows??? I see a bunch of them...

**Comment by andpor** [comment]
When is this going to get merged?

**Comment by bradbumbalough** [comment]
We are facing this issue as well.. please merge. Thank you!

**Comment by bradbumbalough** [comment]
We were able to get a work around for this by injecting `overflow: auto` into our root div. This caused the `scrollParent` to not be `window`, moving the logic to the 2nd block (this line)
https://github.com/facebook/draft-js/blob/0a895226c417dac43c41950be6129e667cab2755/src/component/contents/DraftEditorBlock.react.js#L118 For some reason, even without the `offsetY` code from the PR #1223, this style injection works. It has been an intermittent issue whenever the rendering component was in an iframe, so the style injection code is only invoked in those edge cases.

**Comment by andpor** [comment]
Almost two months have passed and this PR is still not merged...despite multiple people raising the defect...any reason why this is still not merged ?

**Comment by andpor** [comment]
4 months have passed a the PR is still open. Why has it not been merged yet ??????

**Comment by maerzhase** [comment]
@andpor as @bradbumbalough wrote on Sep 6 you can have a work-around fix until the fix is merged.

> We were able to get a work around for this by injecting overflow: auto into our root div.

**Comment by michelson** [comment]
I can confirm that 
```
.DraftEditor-root {
  position: relative;
}
```
fixes the issue

**Comment by maerzhase** [comment]
@michelson didn't test this but for me 
```
.DraftEditor-root {
  overflow: auto;
}
```

**Comment by michelson** [comment]
@maerzhase , whoops , I meant `overflow: auto;` works , I misstyped the style, I've corrected now

**Comment by andpor** [comment]
I think the fix has been incorporated into draftjs codebase somehow although  PR does not appear as merged. 

overflow: auto may not be a suitable comprehensive solution if a use case, as it is for me, requires that the editor grows without scrollbars as more content is entered into it...

**Comment by jackyho112** [comment]
The issue seems to have been fixed now. I could not reproduce the issue right now. 

![nj6dfwjjxg](https://user-images.githubusercontent.com/25375401/32695259-3327e54a-c70b-11e7-80f2-173aea8bb4fb.gif)

Closing the issue for now.

**Comment by ukrbublik** [comment]
This issue still exists. Can easily reproduce it on draftjs.org.
Just try to insert huge block with height > window height (better 2x height :) ) and split it with Enter.

**Comment by thibaudcolas** [comment]
This still seems to happen consistently if the paragraph is big enough. GIF:

![draftjs-big-block-scroll-issue](https://user-images.githubusercontent.com/877585/34654426-0fc3a230-f404-11e7-8efe-d73ac93f5228.gif)

In this example, the paragraph was 9000 chars long.

**Comment by justinlazaro-ubidy** [comment]
Any updates?

**Comment by Arinteck** [comment]
We're steel waiting for fix. :(

**Comment by thibaudcolas** [comment]
> https://github.com/facebook/draft-js/pull/1223#issuecomment-427669940

From what I can see what's missing here is for someone to rebase the existing PR and fix the conflicts. @justinlazaro-ubidy @Arinteck could either of you attempt this if you want it fixed?

**Comment by huchangfa123** [comment]
set DraftEditor-root overflow auto is useful, if use css-module need add : global
```
:global(.DraftEditor-root) {
  overflow: auto;
}
```
is fixed

**Comment by lucasvmiguel** [comment]
> @michelson didn't test your solution — but for me
> 
> ```
> .DraftEditor-root {
>   overflow: auto;
> }
> ```
> works

Didn't work for me... =(

**Comment by andpor** [comment]
@lucasvmiguel not surprised.... my approach seems like the only one that really works but it has taken VERY long time to be merged....why? i do not know....

@thibaudcolas what is the latest? why is this taking so long??

**Comment by thibaudcolas** [comment]
@andpor not sure why you @-me, I have no idea! This is probably better asked on the PR than here. If you want my two cents, looking at the PR, no matter how small you think the change is I'm pretty sure it would be useful if you:

- Fixed the build. I can see two failures: https://travis-ci.org/facebook/draft-js/builds/501979548
- Described the fix in the PR, and perhaps as a comment directly in the code as well. It's pretty hard to know what to make of the change if you just describe it as "Minor code change. No impact on any other code.".
- Added some unit tests for this, so there are no regressions in the future.
- I also see you've replaced `const` keywords by `var`, which doesn't seem like a desirable change.

**Comment by ukrbublik** [comment]
You can take unit tests from my PR: https://github.com/facebook/draft-js/pull/1598

**Comment by crowicked** [comment]
Submitted a PR based on @andpor's PR, just fixed the typo/extra space.
Hope this gets merged soon.

**Comment by harvey88** [comment]
This bug is produced if I click enter with huge text. I added text in editor, then click the enter and cursor moves to the end. https://draftjs.org/. Amount symbols 31560
