### ISSUE TITLE
Draft Editor placeholder pushes caret to next line before text entry...

### ISSUE THREAD

**Issue by steviesama** [facebook/draft-js#403]
In addition to the other issue, when you click on the part of the content area where the placeholder is, you can't put the text cursor focus there. You have to click on the line under the placeholder and the cursor appears there. As soon as you type, the placeholder goes away and the cursor jumps up to where it should have been to begin with.

![nextlineentry](http://i.imgur.com/HZXS7hg.png)

And the render method:
![rendermethod](http://i.imgur.com/gedbML6.png)

**Comment by nie-xin** [comment]
I got the same problem, any idea?

**Comment by steviesama** [comment]
I've gotten tired on looking for a solution. At least in my case a placeholder isn't necessarily important. It is annoying though. 8*/ If someone addresses this issue, that'd be cool though. xD

**Comment by gdehmlow** [comment]
In "Issues and Pitfalls", [they write that](https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#missing-draft-css) there might some problems if you don't include `Draft.css`. I have this same issue, but it's resolved by adding `position: absolute` to the `.public-DraftEditorPlaceholder-root` css class, which is found [in this file](https://github.com/facebook/draft-js/blob/67c5e69499e3b0c149ce83b004872afdf4180463/src/component/base/DraftEditorPlaceholder.css).

**Comment by steviesama** [comment]
I tried the position: absolute thing. It had no effect for me.

**Comment by steviesama** [comment]
Ok...part of it was Draft.css, but not because I didn't include it. I'm using webpack for one, and if you include the css, it renames all of the class names with the appended identifiers, and considering that draft.js is generating the class names dynamically, they weren't on statically defined elements most likely for it to transforms the element classname references.

I inspected it in chrome, and the draft generated classnames are normal but the includes file was mangled; if you use require(./Draft.css) that is. The resolution is to remove that, put the Draft.css in your root directory. And if using express, use `app.use(express.static('.'));` in your server.js so you can add a link tag to Draft.css in your index.html so you can reference files on the server from html.

However, you will still have the caret/cursor being on the next line problem with the placeholder text up. The problem there is I had the focus code in the wrong place. I'll add a screen shot of my changes below. What fixed it is writing the focus method, and making sure it is referenced by the editor containing div's onClick event handler. Div's can't be focused, so be sure it's click, and link it to focus, which puts focus on the editor, the editor has to have the `ref="editor"` in order for this to work.

**Comment by tridungbk2010** [comment]
The Problem is so simple cause of style  "Draft.css", i copied that file and put directly to my component's directory => this problem is resolved :D

**Comment by steviesama** [comment]
@tridungbk2010 Draft.css only fixed part of it in my issue. Most of it was caret behavior, which the css didn't fix.

**Comment by Radivarig** [comment]
@steviesama works for me with [this css](https://github.com/facebook/draft-js/blob/67c5e69499e3b0c149ce83b004872afdf4180463/src/component/base/DraftEditorPlaceholder.css)

**Comment by steviesama** [comment]
@Radivarig Yea. the Draft.css did the trick for me. The caret behavior was code related though. There were some bugs I ran into. I worked around them though.

**Comment by nikhildaga** [comment]
Facing the same issue. @steviesama : How did you solve it?

**Comment by AkyunaAkish** [comment]
I found this works better for me because once the container starts to scroll, position absolute with the placeholder causes the placeholder not to scroll with the container.

```css   
.DraftEditor-editorContainer {
      margin-top: -20px;
}

.public-DraftEditorPlaceholder-root {
      color: rgb(186, 186, 193);
      padding-top: 3px;
      padding-left: 3px;
}
```

**Comment by AkyunaAkish** [comment]
This worked for me better than position absolute for when the editor begins to scroll. 

```css
.public-DraftEditorPlaceholder-root {
      color: rgb(186, 186, 193);
      padding-top: 3px;
      padding-left: 3px;
      margin-bottom: -20px;
}
```

**Comment by abheist** [comment]
Just import `Draft.css` from `draft-js` module.
```
import 'draft-js/dist/Draft.css';
```
Good luck ✌️
